[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
approx = "0.5.1"
image = "0.24.7"

[dev-dependencies]
pretty_assertions = "1.4.0"
